version: "3.6"

services:
        site:
                image: site
                container_name: site
                restart: always
                ports:
                        - 8080:80

        balance:
                image: balance
                container_name: balance
                restart: always
                ports:
                        - 80:80


